services:
  ytpi:
    build: .
    container_name: ytpi
    ports:
      - "7435:7434"
    volumes:
    - type: bind
      source: /mediajf
      target: /app/downloads    
    restart: unless-stopped
