services:
  ytpi:
    build: .
    container_name: ytpi
    network_mode: "host"
    ports:
      - "7435:7434"
    volumes:
      - /mnt/usb0/samsung/media/YouTube:/app/downloads/YouTube
      - '/mnt/usb0/samsung/media/Music Videos':/app/downloads/Music-Videos
    restart: unless-stopped