#single URL example
POST /download HTTP/1.1
Host: localhost:7434
Content-Type: application/json

{
  "url": "https://youtu.be/AQ0P7R9CfCY?si=bK06gTul-0nilOmB"
}

### Single URL Example

# multiple URLs example
POST /download HTTP/1.1
Host: localhost:7434
Content-Type: application/json

{
  "urls": [
            "https://www.youtube.com/playlist?list=PLrLEqwuz-mRKxFJJWulYDvl-gt61oKxf0",
            "https://www.youtube.com/playlist?list=PL6tW9BrhiPTCDteflzehKS6Cn3a79-iCs"
          ]
}

###

#single URL example
POST /download HTTP/1.1
Host: pi.local:7434
Content-Type: application/json

{
  "url": "https://youtu.be/AQ0P7R9CfCY?si=bK06gTul-0nilOmB"
}