# testing runner on new server
# 
name: ytpi-workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Python virtual environment
        run: |
          /usr/bin/python3.11 -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip

      - name: be Copy files to folder
        run: |
          cp -r ${{github.workspace}}/* /home/joe/services/ytpi
      
      - name: Install dependencies
        run: |
          cd /home/joe/services/ytpi
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install --upgrade yt-dlp
      - name: Restart Service
        run: |
          sudo systemctl restart ytpi.service
          sleep 5
          sudo systemctl status ytpi.service


