# testing runner on new server
# 
name: ytpi-docker-workflow

on: workflow_dispatch

env:
  APP_DIR: /home/runneruser/services/ytpi-docker
  
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to folder
        run: |
          rsync -av --delete \
            --exclude='.devcontainer/' \
            --exclude='.github/' \
            --exclude='_archived/' \
            --exclude='.vscode/' \
            --exclude='.git/' \
            --exclude='data/' \
            ${{github.workspace}}/ ${{env.APP_DIR}}/

      - name: Build and Run Docker Container
        run: |
          cd ${{env.APP_DIR}}
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pytest -q
          docker compose up -d --build


